project:
  name: linting-and-testing-workshop
  package_lambda: false
  # Update this section with regions you wish to use
  regions:
  - us-east-1
  - us-west-2
tests:
  default:
    template: ./vpc-and-security-group.yaml
